### ISSUE TITLE
How to fix this error: NameError: name 'BaselinePolicyRollout' is not defined?

### ISSUE THREAD

**Issue by kangjiaxu639** [xinranliang/alp#1]
I tried to run the run_rnd_alp.sh using one 2080TI GPU, but when I run `bash scripts/pretrain/run_rnd_alp.sh 0 1`, this error occured.
```
Traceback (most recent call last):
  File "src/pretrain/run_ddppo.py", line 100, in <module>
    main()
  File "src/pretrain/run_ddppo.py", line 62, in main
    run_exp(**vars(args))
  File "src/pretrain/run_ddppo.py", line 92, in run_exp
    trainer.train()
  File "/home/ros/kjx/alp/habitat-lab/habitat_baselines/rl/ddppo/algo/ddppo_trainer_reward_actpred.py", line 517, in train
    self.world_size
  File "/home/ros/kjx/alp/habitat-lab/habitat_baselines/common/semantic_utils.py", line 362, in main
    actor_critic = BaselinePolicyRollout(
NameError: name 'BaselinePolicyRollout' is not defined
```

I want to know how to fix this error. Thank you

**Comment by xinranliang** [comment]
It seems to be a missing import problem when cleaning up the code. I just pushed an update which should be able to fix this issue.
